language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --prefer-source --no-interaction --dev

script: phpunit

after_success:
  - vendor/bin/coveralls
